### ISSUE TITLE
Convert Todoist Text Formatting

### ISSUE THREAD

**Issue by crookedneighbor** [kusold/todoist-habitrpg#16]
Todoist has some text formatting options, [some of which are actually documented](http://todoist.com/Help/viewHelp?page=format_syntax). In addition to bold, italic and links, you can also highlight `%(hl) foo%` and underline `%(u) bar%`.

Markdown doesn't do underlines, I don't think, but highlighting could be used for code.  

Would be great to convert **bold**, _italic_, `highlighting` and [links](http://todoist.com/Help/viewHelp?page=format_syntax) from Todoist's way of doing them to markdown, so the formatting persists in Habit RPG.

Here's a checklist of things:
- [ ] Highlights `%(hl) foo%`
- [ ] Underlines `%(u) bar%`
- [ ] Links: `http://google.com/ (Google)`
- [ ] Italic: `__Italic text__`
- [ ] Bold: `!!Bold text!!`
- [ ] Outlook Link: `[[outlook=id3=aWQ9MDAwMDAwMDBCOTYzOTQ4N0Y2RDQ2QTQ5OTVBMzM4QjdEMTdDQ0U2NzA3MDA1Q0I1QUY4OTNFQjYyRDRCOEVEOTQ4NkI2QURCNjlERTAwMDAwMDg4Q0Q3NzAwMDA1Q0I1QUY4OTNFQjYyRDRCOEVEOTQ4NkI2QURCNjlERTAwMDAwMEFGNTAyQjAwMDA7bWlkPTxGM0UxNERBOUM5MTQ4NzRGODQ3RjkwRDNFRkJBRkYzQzE1QjE4Q0BNRVItRVhDSDIubmFwaWVyLmFjLnVrPg==, Actual Text goes here]]`

**Comment by crookedneighbor** [comment]
Edited my comment to include a checklist, and added @cygnoir's issue about outlook from #35

**Comment by cygnoir** [comment]
Hi there. I am checking on the status of this, and wanted to add the Postbox link format too: 
`[[thunderbird Actual text goes here 18DF859FE41AA145A9A55ED839BB10D55687FFF8@W2K8-MAILBOX.natlibofscot.nls.uk   ]]`
