### ISSUE TITLE
Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by castor-troy** [kusold/todoist-habitrpg#38]
When I am trying to sync for the second time, I get this error.

Sync failed with error: Error: Hostname/IP doesn't match certificate's altnames
Sync completed successfully.

**Comment by InfH** [comment]
After multiple syncs, I have this issue as well.

**Comment by kusold** [comment]
This appears to be a network issue or an issue at the time with either HabitRPG or Todoist's SSL cert.

I'm going to close this, but please let me know if you are still getting it.
