### ISSUE TITLE
Test Version 3 of the API

### ISSUE THREAD

**Issue by crookedneighbor** [kusold/todoist-habitrpg#40]
We're looking for Habitica developers to try out the upcoming version 3 of the API. We are hoping that we will be ready to start testing within the next two weeks, but we're collecting testers now so that we can hit the ground running. Thanks very much for considering it, and feel free to let me know if you have any questions!

| [Sign Up!](https://docs.google.com/forms/d/1xXxZvSviR_s8K3I31bKXH6Dfc6Ud9TuTG66I90PdwQI/viewform) |
|---|

**Comment by kusold** [comment]
Just updated to the latest API. It was fairly painfree. I made a shim as an option to make migrating more painless.
