### ISSUE TITLE
Sync fails with timeout

### ISSUE THREAD

**Issue by ajfclark** [kusold/todoist-habitrpg#41]
When I attempt to sync, I get a timeout error:
```
$ todoist-habitrpg -u [uid] -t [token] -a [token]
Sync failed with error: Error: connect ETIMEDOUT 54.243.175.97:443
Sync completed successfully.
$
```
Repeated attempts just result in Habitica lists the same To-dos multiple times, sometimes getting further through the sync, but always failing.

Various hosts are reported. Thus far I've seen:
```
Sync failed with error: Error: connect ETIMEDOUT 54.235.146.150:443
Sync failed with error: Error: connect ETIMEDOUT 54.243.175.97:443
Sync failed with error: Error: connect ETIMEDOUT 50.16.225.80:443
Sync failed with error: Error: connect ETIMEDOUT 50.16.225.80:443
Sync failed with error: Error: connect ETIMEDOUT 52.200.13.212:443
```

I can't find a log file anywhere, regardless of whether I point -f to a directory as indicated in the README or a file as indicated in the --help blurb.

**Comment by kusold** [comment]
@ajfclark This should be resolved. Let me know if the issue persists.

**Comment by ajfclark** [comment]
Confirmed that sync no longer times out for me.

Thanks!
