### ISSUE TITLE
Says it synced but didn't

### ISSUE THREAD

**Issue by achimbarczok** [kusold/todoist-habitrpg#42]
Since the project has not been updated for a while I am not sure if it still is maintained. I get successful Sync notifications whether the used Tokens are right or wrong. The Sync Log tells me it didn't sync

**Comment by eringiglio** [comment]
It's the API not being updated and the new one going into effect this past week, I'm afraid. I'd tweak it and submit a pull request, but I don't actually know enough javascript to identify the API issues. I'm currently trying to work on something similar in Python, but I'm moving fairly slowly on that.

**Comment by achimbarczok** [comment]
solved with new version
