### ISSUE TITLE
daily in todoist not recognised in habitica

### ISSUE THREAD

**Issue by ajfclark** [kusold/todoist-habitrpg#49]
I created a task in todoist to be repeated `daily` and it showed up as a to-do in habitica, not a daily.

Deleting it can changing the repeat to `every day` and it showed up correctly in habitica.

**Comment by kusold** [comment]
@ajfclark Does this work in todoist? Right now I go off of this page: https://support.todoist.com/hc/en-us/articles/205325931-Dates-and-Times

If it works then I can add support for it.

**Comment by kusold** [comment]
Just saw this line:

> Every day starting from today (daily also works)

**Comment by kusold** [comment]
Fixed in `v1.1.0`.
